FROM python:3.12-slim

WORKDIR /app

COPY requirements ./requirements
RUN pip install --no-cache-dir -r requirements

COPY main.py ./main.py

EXPOSE 8001

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
