FROM python:3.12-slim

WORKDIR /app

COPY requirements ./requirements
COPY requirements-test.txt ./requirements-test.txt
RUN pip install --no-cache-dir -r requirements-test.txt

COPY main.py ./main.py
COPY tests ./tests

EXPOSE 8001

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8001"]
